### ISSUE TITLE
Create a document collection called users using a User object and create a UserRepository interface and implementation

### ISSUE THREAD

**Issue by SDiamante13** [logunlaja26/budget-tracker#1]
```json
{
  "id": 1,
  "date": "5-14-2020",
  "amount": 42,
  "type": "EXPENSE",
  "category": "SHOPPING",
  "description": "A toy chest"
}
```

id:
    type: integer
  date:
    type: string
  amount:
    type: integer
  type:
    type: string
    enum:
      - INCOME
      - EXPENSE
  category:
    type: string
    enum:
      - GROCERIES
      - ENTERTAINMENT
      - UTILITIES
      - PAYCHECK
      - RENT
      - MORTGAGE
      - OTHER
      - SHOPPING
  description:
    type: string
required:
  - amount
  - type
  - category

**Comment by SDiamante13** [comment]
User will have the following fields: 

```
String id
String username
List <Expense>
```

(eventually we will add list of income as well)

Use `@Indexed` for any fields that need to be queried against.

 -----------------------------------------------------------
Expense will have the following fields:

   Long expenseId
    LocalDate transactionDate
    double amount
    Category category
    String description

ExpenseId is important to facilitate deletes. You must know which expense to delete.

------------------------------------------------------------------------------------

Here is the interface UserRepository: (is it up to you to fulfill the implementations of these methods)

public interface UserRepository {
    void createUser(User user);
    void updateExpenses(String username, Expense expense);
    Optional<User> findUserByUsername(String username);
    void deleteExpense(String username, long expenseId);
}

While writing test your implementation using an embedded Mongo database.

Here is a hint to get you started:

```java
@ExtendWith(SpringExtension.class)
@DataMongoTest
class UserRepositoryIntegrationTest {

    @Autowired
    private MongoTemplate mongoTemplate;

    private UserRepository userRepository;

    @BeforeEach
    void setUp() {
        userRepository = new UserRepositoryImpl(mongoTemplate);
```

To insert test data you can use `mongoTemplate.insert(new User(), "users")`
* "users" is the collection name

Use MongoTemplate to interact with the database.
[Intro to MongoDB](https://www.baeldung.com/spring-data-mongodb-tutorial)

Consider error cases, for example while updatingExpenses you would want to make sure the user exists in the database if not you should throw an exception. You can use Assertion statements which throw IllegalArgumentExceptions. 

[Spring Assert Statements](https://www.baeldung.com/spring-assert)

**Comment by SDiamante13** [comment]
https://www.devglan.com/spring-boot/spring-data-mongodb-queries

**Comment by SDiamante13** [comment]
I researched about using @DbRef but it is a bad practice. Instead of embedding expenses it will be more flexible to have it as its own separate collection. 

```java
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Document(collection = "users")
public class User {
    @Id
    private String id;

    @Indexed(unique = true)
    private String username;

    @Indexed
    private List<ObjectId> expenseIds;
}
```

```java
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Document(collection = "expenses")
public class Expense {
    @Id
    private ObjectId expenseId;
    @Indexed
    private LocalDate transactionDate = LocalDate.now();
    private double amount;
    @Indexed
    private Category category;
    private String description;
}
```

**UserRepository**
```java
    void createUser(String username);
    void updateExpenses(String username, Expense expense);
    Optional<User> findUserByUsername(String username);
    void deleteExpense(String username, ObjectId expenseId);
```

**Comment by SDiamante13** [comment]
This design is not good and has the same issue. Gonna stick with the previous design. Will do the filtering after grabbing all the expenses.

**Comment by logunlaja26** [comment]
@SDiamante13 Ok, sounds like a plan.

**Comment by SDiamante13** [comment]
New Model:
**User**

```java
@Id
private String id;
@Indexed(unique = true)
private String username;
```

**Expense**
```java
   @Id
    private String expenseId;
    @Indexed
    private String username;
    @Indexed
    @Builder.Default
    private LocalDate transactionDate = LocalDate.now();
    private double amount;
    @Indexed
    private Category category;
    private String description;
```

### Explanation

Expenses refer to a username. It is now easy to add expenses, you'll just need to include who's expense it is. I am happy with this new data model and it should make things much easier.


**Repositories**

```java
public interface UserRepository {
    void createUser(String username);
}
```

```java
public interface ExpenseRepository {
    Expense addExpense(Expense expense);
    List<Expense> findAllExpensesByUsername(String username);
    Expense updateExpense(Expense expense);
    void deleteExpense(String expenseId);
    List<Expense> getExpensesByCategoryAndMonth(String username, Category category, Month month);
}
```
